// ===================================================================
// @AI-CRITICAL-RULES: 核心数据结构定义层
//
// 本文件定义了系统所有持久化数据的 TypeScript 接口，是数据库表结构
// 的"单一事实来源"(Single Source of Truth)。这些接口直接映射到
// IndexedDB Object Stores 和 Electron 文件存储的 JSON 结构。
//
// ■ 绝对禁止的操作：
//   1. 删除或重命名任何现有字段 —— 会导致已持久化的用户数据损坏。
//   2. 修改现有字段的类型 —— 会导致数据库迁移冲突和运行时错误。
//   3. 移除或缩减接口 —— 下游代码、数据库 schema、导入导出逻辑
//      均依赖这些类型定义。
//
// ■ 允许的扩展方式（仅限以下两种）：
//   1. 在现有接口末尾追加可选字段（?）。
//   2. 新建独立的接口 / 类型，并在对应的数据库 Store 中创建新表。
//
// ■ 修改前必读文件：
//   - src/services/db.ts（数据库实现 & IndexedDB schema 版本管理）
//   - src/composables/useEntries.ts（条目 CRUD 核心逻辑）
//   - electron/main.cjs（Electron 端文件存储 & 级联删除）
//
// VIOLATION OF THESE RULES WILL CAUSE DATA CORRUPTION.
// ===================================================================
export interface Notebook {
  id: string
  name: string
  description: string
  instructions: string
  sortOrder?: number
  createdAt: number
  updatedAt: number
}

export interface NoteEntry {
  id: string
  notebookId: string
  title: string
  question: string
  wrongAnswer: string
  correctAnswer: string
  subject: string
  source: string
  tags: string[]
  sortOrder?: number
  createdAt: number
  updatedAt: number
  // SRS fields
  reviewCount?: number
  consecutivePasses?: number
  masteryLevel?: number
  easeFactor?: number
  interval?: number
  lastReviewDate?: number
  nextReviewDate?: number
  // Canvas drawings (per-field data URLs)
  drawings?: Record<string, string>
  // 归属的知识库；未设置则默认 'notes'
  kbId?: string
  // Optional origin metadata for entries generated by an installed notebook plugin.
  pluginSource?: {
    pluginId: string
    archiveId: string
    wordId: string
    reviewMode: 'zh-to-en' | 'en-to-zh'
    wrongCount: number
    lastWrongAt: number
  }
}

export interface ReviewLog {
  id: string
  entryId: string
  timestamp: number
  quality: number | string
  // 选择题作答结果；旧记录没有这些字段时仍可正常使用。
  selectedChoice?: string
  correctChoice?: string
  isCorrect?: boolean
  // 复习场次信息；用于在统计面板按“到期 / 自由复习”展示已完成的复习历史。
  sessionId?: string
  reviewScope?: 'due' | 'all'
  sessionSize?: number
  sessionCompleted?: boolean
  elapsedMs?: number
  reviewNote?: string
}

/**
 * AI 指令（skill）—— 用户在 AI 问答输入框敲 /<trigger> 触发。
 * systemPrompt 会替换默认 system，让 AI 按你想要的方式回答。
 * scope=entry 仅在错题模式可用；global 仅全库；both 都可用。
 */
export interface AiSkill {
  id: string
  name: string
  trigger: string
  description?: string
  systemPrompt: string
  scope: 'entry' | 'global' | 'both'
  enabled: boolean
  updatedAt: number
}
